#6 Stworzenie klas encji Type, Grade i bazowej struktury C-S-R
skni-kod/KodemyBackend pull request #11
Opened 2022-12-26 13:36 UTC by OskarN8

2022-12-26 18:29 UTC, KartVen requested changes

2022-12-26 18:29 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/KodemyBackendApplication.java
> +	private final TypeRepository typeRepository;
Nie powinno się zostawiać w kodzie nieużywanego kodu, gdyż później robi się bałagan.

2022-12-26 18:29 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/grade/Grade.java
> +@Table(name = "grade")
Podstawowo encja tworzy tabelę zgodnie z nazwą klasy. Aby kod był spójny w całym projekcie polecam tą linijkę usunąć.

2022-12-26 18:29 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/grade/Grade.java
> +//    }
Trzymaj się konwencji zostawiania odstępów pomiędzy metodami i spójności wyglądu kodu.

2022-12-26 18:29 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/grade/Grade.java
> +    public Grade(long id) {
Ten konstruktor jest niepotrzebny, co w zasadzie umożliwia użycie konstruktora domyślnego bez konieczności jego definiowania.

2022-12-26 18:29 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/grade/Grade.java
> +
Niepotrzebne linie.

2022-12-26 18:29 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/type/Type.java
> +@Table(name = "type")
Identyczna sytuacja co w encji Grade.

2022-12-26 18:29 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/type/Type.java
> +
Niepotrzebna linia.

2022-12-26 18:29 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/type/TypeService.java
> +
To samo co w pliku GradeService.

2022-12-26 18:29 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/grade/GradeService.java
> +
Nie potrzebny odstęp. Co prawda klasa będzie jeszcze edytowana, ale warto zachować jakąś spójną konwencję.

2022-12-26 18:39 UTC, KartVen requested changes
Trochę powrzucałeś niepotrzebnych plików.

2022-12-27 17:27 UTC, OskarN8 commented on src/main/java/pl/sknikod/kodemy/KodemyBackendApplication.java
> +	private final TypeRepository typeRepository;
fix

2022-12-27 17:27 UTC, OskarN8 commented on src/main/java/pl/sknikod/kodemy/grade/Grade.java
> +@Table(name = "grade")
fix

2022-12-27 17:27 UTC, OskarN8 commented on src/main/java/pl/sknikod/kodemy/grade/Grade.java
> +//    }
fix

2022-12-27 17:27 UTC, OskarN8 commented on src/main/java/pl/sknikod/kodemy/grade/Grade.java
> +    public Grade(long id) {
fix

2022-12-27 17:27 UTC, OskarN8 commented on src/main/java/pl/sknikod/kodemy/grade/Grade.java
> +
fix

2022-12-27 17:28 UTC, OskarN8 commented on src/main/java/pl/sknikod/kodemy/type/Type.java
> +@Table(name = "type")
fix

2022-12-27 17:28 UTC, OskarN8 commented on src/main/java/pl/sknikod/kodemy/type/Type.java
> +
fix

2022-12-27 19:35 UTC, merged