#52 Endpoint dodawanie oceny do materiału/ wyswietlanie ocen materialu
skni-kod/KodemyBackend pull request #56
Opened 2023-04-17 16:17 UTC by oniedzialek

2023-04-17 20:19 UTC, KartVen requested changes

2023-04-17 20:19 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/material/MaterialService.java
> +                .getOrElseThrow(() -> new GeneralRuntimeException("Failed to processing"));
Mogłem ja to zrobić, ale przy okazji popraw można stworzyć nowy konstruktor w bazowym wyjątku, automatycznie wstawiający message "Failed...". W miarę możliwości podmienić w pozostałych plikach.

2023-04-17 20:19 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/rest/mapper/GradeMapper.java
> +            @Mapping(target = "grade", source = "grade"),
Mapowianie pól o tych samych nazwach i typach nie potrzebuje dodatkowej adnotacji, wymagajacej później ich przetwarzania.

2023-04-17 20:19 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/rest/request/MaterialAddGradeRequest.java
> +    @Pattern(regexp = "^(1|1\\.5|2|2\\.5|3|3\\.5|4|4\\.5|5)$")
Próbowałeś: `^[0-5](\.[05])?$`?
Dodatkowo dlaczego wartość jest łańcuchem?

2023-04-17 20:19 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/rest/response/MaterialShowGradesResponse.java
> +    private Set<GradeResponse> grades;
Z tego co pamiętam ustalaliśmy, że będziemy zwracać czysto listę, zatem w tym przypadku najlepiej będzie zrobić klasę `GradeResponse` jako podstawową z nazwą `SingleGradeResponse`, a w ResponseEntity zwracać `Set<SingleGradeResponse>`.
Unikniemy w takiej sytuacji pola o niepotrzebnej roli segregatora.
Oczywiście jeśli się mylę, to daj znać.

2023-04-17 20:19 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/rest/response/MaterialShowGradesResponse.java
> +            this.createdBy = new UserResponse(createdBy.getId(), createdBy.getUsername());
Zamiast jawnie nadpisywać zmienną polecam wykorzystać pole encji Grade z wykorzystaniem mapowania.
Dodatkowo polecam ustawiać wszystkie klasy odpowiedzi jako `@Value`.

2023-04-17 20:19 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/rest/response/MaterialShowGradesResponse.java
> +    public MaterialShowGradesResponse(Set<Grade> grades) {
Tą konwersją powinien się zająć mapper.

2023-04-20 16:27 UTC, oniedzialek commented on src/main/java/pl/sknikod/kodemy/rest/request/MaterialAddGradeRequest.java
> +    @Pattern(regexp = "^(1|1\\.5|2|2\\.5|3|3\\.5|4|4\\.5|5)$")
String bo Double, nie wchodzi. @Pattern jest zarezerwowane dla String (?)

2023-04-20 18:42 UTC, KartVen commented on src/main/java/pl/sknikod/kodemy/material/MaterialController.java
> +    public ResponseEntity<MaterialShowGradesResponse> showGrades(@PathVariable Long materialId) {
Sorki, nieprecyzyjne info. Chodziło mi o zmienną gradesResponse:
```java
return ResponseEntity.ok().body(materialService.showGrades(materialId));
```

2023-05-05 11:39 UTC, KartVen approved these changes

2023-05-05 11:40 UTC, merged